config/routes.rb
Rails.application.routes.draw do
    root :to => 'home#index'

  devise_for :users
    resources :posts do
      resources :comments
    end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :username, :presence => true
  validates :description, :presence => true
  after_save :send_message

private

  def send_message
    if self.post.user.phone
    begin
      response = RestClient::Request.new(
      method: :post,
      url: "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
      user: ENV['TWILIO_ACCOUNT_SID'],
      password: ENV['TWILIO_AUTH_TOKEN'],
      payload: {  Body: "User #{self.username} just commented on your post",
                  To: self.post.user.phone,
                  From: ENV['TWILIO_NUMBER'] }
        ).execute
      rescue
        false
      end
    end
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  before_create :send_message

  # def send
  #   self.send_message
  # end

  private

  def send_message
    begin
      response = RestClient::Request.new(
        :method => :post,
        :url => "https://api.twilio.com/2010-04-03/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :Body => body,
                      :To => to,
                      :From => from}
      ).execute
    rescue  
      false
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  validates :entry, :presence => true
  validates :title, :presence => true
  validates :date, :presence => true


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  validates :email, :presence => true
  validates :phone, :presence => true
  validates :password, :presence => true
  validates :password_confirmation, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :phone
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def show
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def index
    @comments = Comment.all
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.destroy
      flash[:alert] = "Comment successfully deleted"
    end
    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:notice] = "Task successfully updated!"
      redirect_to post_path(@comment.post)
    else
      render :edit
    end
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "Your Comment has been saved successfully"
      respond_to do |format|
        format.html { redirect_to post_path(@post) }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path }
        flash[:alert] = "There was a problem creating this comment"
        format.js
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:post_id, :username, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:alert] = "Post successfully deleted"
    end
    redirect_to posts_path
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Task successfully updated!"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = "Your post has been saved successfully"
      redirect_to post_path(@post)
    else
      flash[:alert] = "There was a problem creating this post"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :entry, :date, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<ul>
  <li class="comment" id="comment_<%= comment.id %>">
    <%= comment.description %>,<br>
    <%= comment.username %>
    <%= link_to "Edit Comment", edit_post_comment_path(@post, comment) %> |
    <%= link_to "Delete Comment", post_comment_path(@post, comment),
    :data => {:confirm => "You sure?",
    :method => "delete"} %> |
</ul>

app/views/comments/_form.html.erb
<div class="container">
  <h1> Craft a Comment! </h1>
  <%= form_for [@post, @comment], remote: true do |f| %>
  <div>
  <%= f.hidden_field :username, value: current_user.email %>
  </div>
  <div>
  <%= f.label :description  %>
  <%= f.text_area :description, :required => true %>
  </div>
  <%= f.submit "Post Comment" %>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#new_comment').remove();
$('#new_link').show();
$('#all_comments').prepend('<%= j render(@comment) %>');

app/views/comments/edit.html.erb
<% content_for(:title, "Edit | comment") %>
<%= render 'layouts/errors', object: @comment %>

<h1>Edit the Comment</h1>

<div class="container">
  <%= form_for [@post, @comment] do |f| %>
  <div>
    <%= f.label :username %>
    <%= f.text_field :username, :required => true %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description, :required => true %>
  </div>
  <%= f.submit "Edit comment" %>
  <% end %>
</div>

app/views/comments/new.html.erb
<%= render 'layouts/errors', object: @comment %>
<%= render 'form' %>

app/views/comments/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/home/index.html.erb
<ul class="nav nav-pills">
  <div>
    <li><h3><%= link_to "Craft Post", new_post_path, :class => 'navbar-post' %></h3></li>
    <li><h3><%= link_to "Sign in", new_user_session_path,  :class => 'navbar-signin' %></h3></li>
  </div>
</ul>

<h1>Coffee Achiever's</h1>

<h3>Click <%= link_to "here", posts_path%> to view all posts</h2>
<ul class="nav nav-pills">
<li><h3><%= link_to "Log out", destroy_user_session_path, :method => "DELETE" %></h2></li>
</ul>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoffeeBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="photo" class="container">
    <div class="jumbotron">

<%= yield %>

<%=  flash[:notice] %>
<%=  flash[:alert] %>

    </div>
  </div>
</body>
</html>

app/views/posts/edit.html.erb
<% content_for(:title, "Edit | Post") %>
<%= render 'layouts/errors', object: @post %>

<h1>Edit the Post: <%= @post.title %> </h1>

<div class="container">
  <%= form_for @post do |f| %>
  <div>
  <%= f.label :title %>
  <%= f.text_field :title, :required => true %>
  </div>

  <div>
  <%= f.label :entry %>
  <%= f.text_area :entry, :required => true %>
  </div>
  <div>
  <%= f.label :date %>
  <%= f.date_field :date, :required => true %>
  </div>
  <%= f.submit "Edit Post" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <h1>Coffee Achievements</h1>
</div>
<h3>Posts</h3>
<div>
<% @posts.each do |post| %>
    <ul>
      <li><%= link_to post.title, post_path(post) %></li>
    </ul>
<% end %>
</div>
<div class="nav nav-pills">
    <li><%= link_to "Add another post", new_post_path %></li>
    <li><%= link_to "Home", root_path %></li>
</div>
</div>

app/views/posts/new.html.erb
<%= render 'layouts/errors', object: @post %>


<div class="container">
  <h1> Craft a Post! </h1>
  <%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :entry %>
  <%= f.text_area :entry %>
  <%= f.hidden_field :date, value: Date.today %>
  <%= f.submit "Post" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div>
<h1><%= @post.title %></h1>
</div>
<div>
  <h2><%= @post.entry %></h2>
</div>
<div>
  <h5><%= @post.date %></h5>
</div>
<div>
  <%= link_to "Edit Post", edit_post_path(@post) %> |
  <%= link_to "Delete Post", post_path,
  :data => {:confirm => "Do you really want to delete this post?",
    :method => "delete"} %>
  </div>


<div>
<h3>Comments</h3>
  <%= link_to "Add a Comment", new_post_comment_path(@post), id: "new_link", remote: true %>
    <div id="all_comments">
    <% @post.comments.each do |comment| %>
    <ul>
      <li><%= comment.username %></li>
      <li><%= comment.description %></li>
      <%= link_to "Edit Comment", edit_post_comment_path(@post, comment) %> |
      <%= link_to "Delete Comment", post_comment_path(@post, comment),
      :data => {:confirm => "You sure?",
        :method => "delete"} %> |
    </ul>
    <% end %>
      <p> Be the first one to comment!</p>
    </div>
    <div>
    <%= link_to "Home", root_path %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>